### ISSUE TITLE
Upgrade to Godot 4

### ISSUE THREAD

**Issue by guerro323** [patanext-project/patanext#65]
## Tasks
- [x] Import project to Godot 4 without errors (not C# related)
- [x] Replace the CLR plugin with the newest one
- [x] Recreate the ECS systems (AppSystem based)

Once done we will be able to continue working on PataNext

**Comment by guerro323** [comment]
All the required tasks are finished, what's left is testing if the repo work on Windows.

(commit https://github.com/patanext-project/patanext/commit/d2553b8e883f4f47918347c33cb69d987b3017b1 and https://github.com/guerro323/that-rhythm-project/commit/29ea9f83f5373cd430508878cc7872bee6036084 (Quadrum))
